# Generated by Django 3.2.23 on 2023-12-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revooz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
